# Generated by Django 3.2.7 on 2022-07-17 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='outlet_logos', verbose_name='Outlet logo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('img', models.ImageField(blank=True, null=True, upload_to='outlet_images', verbose_name='Photo')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outlet_city', to='city.city', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Outlet',
                'verbose_name_plural': 'Outlet',
            },
        ),
        migrations.CreateModel(
            name='OutletImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='outlet_images', verbose_name='Фото')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet_images', to='outlet.outlet')),
            ],
            options={
                'verbose_name_plural': 'Photo outlet',
            },
        ),
    ]
